/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import javax.swing.JOptionPane;
import project_tacion_de_oro.*;

/**
 *
 * @author usuario
 */
public class RegistrarIniciarSesion extends javax.swing.JFrame {
    private  Socio socio;
    /**
     * Creates new form RegistrarIniciarSesion
     */
    public RegistrarIniciarSesion() {
        initComponents();
        visualizacion();
        ini.setVisible(false);
        re.setVisible(false);
    }

    public Socio getSocio() {
        return socio;
    }

    public void setSocio(Socio socio) {
        this.socio = socio;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLNombre = new javax.swing.JLabel();
        jLEmail = new javax.swing.JLabel();
        jLPoblacion = new javax.swing.JLabel();
        jLDireccion = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jTDireccion = new javax.swing.JTextField();
        jTEmail = new javax.swing.JTextField();
        jTPoblacion = new javax.swing.JTextField();
        jLTitulo = new javax.swing.JLabel();
        re = new javax.swing.JButton();
        jRBInicioSesion = new javax.swing.JRadioButton();
        jRBRegistrar = new javax.swing.JRadioButton();
        jTContrasenia1 = new javax.swing.JTextField();
        jLContrasena1 = new javax.swing.JLabel();
        ini = new javax.swing.JButton();
        l_notification = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLNombre.setText("Nombre:");

        jLEmail.setText("Email:");

        jLPoblacion.setText("Poblacion:");

        jLDireccion.setText("Dirección:");

        jTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreActionPerformed(evt);
            }
        });

        jLTitulo.setBackground(new java.awt.Color(0, 204, 0));
        jLTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo.setText("Elejer :");

        re.setBackground(new java.awt.Color(0, 153, 51));
        re.setText("Registarme");
        re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBInicioSesion);
        jRBInicioSesion.setText("Iniciar Sesion");
        jRBInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBInicioSesionActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBRegistrar);
        jRBRegistrar.setText("Registrar");
        jRBRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBRegistrarActionPerformed(evt);
            }
        });

        jLContrasena1.setText("Contraseña:");

        ini.setBackground(new java.awt.Color(0, 153, 51));
        ini.setText("Inciar Sesión");
        ini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniActionPerformed(evt);
            }
        });

        l_notification.setText("..........");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ini, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(re, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLTitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jRBRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRBInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLContrasena1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTContrasenia1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLPoblacion)
                                .addGap(106, 106, 106)
                                .addComponent(jTPoblacion))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLNombre)
                                    .addComponent(jLDireccion))
                                .addGap(109, 109, 109)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTDireccion)
                                    .addComponent(jTNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(l_notification)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBRegistrar)
                    .addComponent(jRBInicioSesion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDireccion)
                    .addComponent(jTDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPoblacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEmail))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLContrasena1)
                    .addComponent(jTContrasenia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(re)
                    .addComponent(ini))
                .addGap(18, 18, 18)
                .addComponent(l_notification)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreActionPerformed

    private void jRBRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBRegistrarActionPerformed
        // TODO add your handling code here:
        visualizacion();
        
        
        re.setVisible(true);
        jLTitulo.setText("Registrar");
            
        jTContrasenia1.setEnabled(true);
        jTDireccion.setEnabled(true);
        jTEmail.setEnabled(true);
        jTNombre.setEnabled(true);
        jTPoblacion.setEnabled(true);
        
        
        //Quito visualizaion de jLabel
        jLContrasena1.setEnabled(true);
       
        jLDireccion.setEnabled(true);
        jLEmail.setEnabled(true);
        jLNombre.setEnabled(true);
        jLPoblacion.setEnabled(true);
        jLTitulo.setEnabled(true);
        ini.setVisible(false);
        re.setVisible(true);
            
            
  
    }//GEN-LAST:event_jRBRegistrarActionPerformed

    private void iniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniActionPerformed
        // TODO add your handling code here:
        Socio in = new Socio(jTEmail.getText().trim(),jTContrasenia1.getText().trim());
        DBsocio db = new DBsocio();
        socio= db.ClienteIn(in);
        if(socio==null){
            
            JOptionPane.showMessageDialog(this, "no existe");
        }else{
            Productos pros = new Productos(this, true);
            pros.setVisible(true);
        }
        
        
        
        
    }//GEN-LAST:event_iniActionPerformed

    private void reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reActionPerformed
        // TODO add your handling code here:
        Socio reg = new Socio();
        reg.registrar(jTNombre.getText(), jTEmail.getText().trim(), jTDireccion.getText(), jTPoblacion.getText(),jTContrasenia1.getText().trim());
             
    }//GEN-LAST:event_reActionPerformed

    private void jRBInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBInicioSesionActionPerformed
        // TODO add your handling code here:
        visualizacion();
        
            jLTitulo.setText("Inicio Sesion");
            ini.setVisible(true);
            jLEmail.setEnabled(true);
            jTEmail.setEnabled(true);
            jLContrasena1.setEnabled(true);
            jTContrasenia1.setEnabled(true);
            re.setVisible(false);
            ini.setVisible(true);
            
        
        
    }//GEN-LAST:event_jRBInicioSesionActionPerformed
    
    private void visualizacion(){
        //Quito visualizacion de jtext
        jTContrasenia1.setEnabled(false);
        jTDireccion.setEnabled(false);
        jTEmail.setEnabled(false);
        jTNombre.setEnabled(false);
        jTPoblacion.setEnabled(false);
        
        
        //Quito visualizaion de jLabel
        jLContrasena1.setEnabled(false);
        
        jLDireccion.setEnabled(false);
        jLEmail.setEnabled(false);
        jLNombre.setEnabled(false);
        jLPoblacion.setEnabled(false);
        jLTitulo.setEnabled(false);
        
        
        
        
//        if(jRBRegistrar.isSelected() == false && jRBInicioSesion.isSelected() == true){
//            jLTitulo.setText("Iniciar Sesión");
//        }
//        if(jRBRegistrar.isSelected() == false && jRBInicioSesion.isSelected() == false){
//            jLTitulo.setText("elige una opción");
//        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarIniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton ini;
    private javax.swing.JLabel jLContrasena1;
    private javax.swing.JLabel jLDireccion;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLPoblacion;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBInicioSesion;
    private javax.swing.JRadioButton jRBRegistrar;
    private javax.swing.JTextField jTContrasenia1;
    private javax.swing.JTextField jTDireccion;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTPoblacion;
    private javax.swing.JLabel l_notification;
    private javax.swing.JButton re;
    // End of variables declaration//GEN-END:variables
}
